In [2]:
import pandas as pd
import matplotlib as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeRegressor

In [190]:
train_data = pd.read_csv("data/training_extra.csv")

In [191]:
mean_price_og = train_data['Price'].mean()

In [192]:
mean_price_og

81.3582010118999

In [193]:
train_data.dropna(axis =0, how= "any", inplace= True)

In [194]:
train_data.columns

Index(['id', 'Brand', 'Material', 'Size', 'Compartments', 'Laptop Compartment',
       'Waterproof', 'Style', 'Color', 'Weight Capacity (kg)', 'Price'],
      dtype='object')

In [195]:
#categorical columns
cat_columns = ['Brand', 'Material', 'Size', 'Laptop Compartment',
       'Waterproof', 'Style', 'Color']

In [196]:
x_train_cat = train_data[cat_columns].values

In [197]:
#enc = OneHotEncoder(drop='first').fit(x_train_cat)
enc = OneHotEncoder(drop='first').fit(train_data[cat_columns])

In [198]:
enc.categories_

[array(['Adidas', 'Jansport', 'Nike', 'Puma', 'Under Armour'], dtype=object),
 array(['Canvas', 'Leather', 'Nylon', 'Polyester'], dtype=object),
 array(['Large', 'Medium', 'Small'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['Backpack', 'Messenger', 'Tote'], dtype=object),
 array(['Black', 'Blue', 'Gray', 'Green', 'Pink', 'Red'], dtype=object)]

In [199]:
train_cat_encoded = enc.transform(train_data[cat_columns])
x_train_cat_encoded = np.array(train_cat_encoded)

In [200]:
x_train_noncat = train_data[['id','Compartments','Weight Capacity (kg)']].values

In [201]:
train_encoded = pd.get_dummies(train_data,columns=cat_columns,drop_first=True)

In [202]:
x_train = train_encoded.drop(['id','Price'],axis=1,inplace=False).values

In [203]:
x_train

array([[10.0, 23.882052195806217, False, ..., False, False, False],
       [4.0, 11.869095352089928, False, ..., True, False, False],
       [8.0, 8.0923022079504, True, ..., False, False, True],
       ...,
       [10.0, 17.37953101741519, False, ..., False, False, False],
       [10.0, 17.037707847062194, True, ..., False, False, True],
       [2.0, 23.07616865301621, False, ..., False, False, False]],
      dtype=object)

In [204]:
train_encoded

,id,Compartments,Weight Capacity (kg),Price,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour,Material_Leather,Material_Nylon,...,Size_Small,Laptop Compartment_Yes,Waterproof_Yes,Style_Messenger,Style_Tote,Color_Blue,Color_Gray,Color_Green,Color_Pink,Color_Red
0,500000,10.0,23.882052,114.11068,False,False,False,True,False,False,...,True,True,True,False,True,True,False,False,False,False
1,500001,4.0,11.869095,129.74972,False,False,True,False,False,False,...,True,False,True,False,False,False,False,True,False,False
2,500002,8.0,8.092302,21.37370,True,False,False,False,False,False,...,True,True,True,False,True,False,False,False,False,True
3,500003,7.0,7.719581,48.09209,False,True,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False
4,500004,9.0,22.741826,77.32461,False,True,False,False,True,False,...,False,False,True,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3694311,4194311,4.0,28.425845,107.18468,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,True,False
3694312,4194312,6.0,16.641739,31.52978,True,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,True
3694314,4194314,10.0,17.379531,122.39043,False,False,True,False,True,False,...,True,True,True,False,True,True,False,False,False,False
3694315,4194315,10.0,17.037708,148.18470,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3694317,4194317,2.0,23.076169,107.61199,False,False,False,True,False,False,...,False,True,False,False,False,True,False,False,False,False

In [205]:
y_train = train_encoded['Price'].values

In [206]:
y_train.reshape(-1,1)

array([[114.11068],
       [129.74972],
       [ 21.3737 ],
       ...,
       [122.39043],
       [148.1847 ],
       [107.61199]])

In [207]:
price_reg = LinearRegression()

In [228]:
price_tree = DecisionTreeRegressor(max_depth=15)
#price_tree = DecisionTreeRegressor(max_depth=10)

In [229]:
price_tree.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=15)

In [230]:
y_pred_train = price_tree.predict(x_train)

In [231]:
y_base1 = [train_data['Price'].mean()]*len(y_train)
y_base_og = [mean_price_og]*len(y_train)

In [232]:
from sklearn.metrics import root_mean_squared_error, mean_squared_error

In [233]:
root_mean_squared_error(y_pred_train,y_train)

38.50431308721578

In [234]:
root_mean_squared_error(y_base1,y_train)

38.81253158911432

In [235]:
root_mean_squared_error(y_base_og,y_train)

38.81273393984873

In [236]:
test_data = pd.read_csv("data/test.csv")

In [237]:
mean_test_weight = test_data['Weight Capacity (kg)'].mean()

In [238]:
test_data.fillna({'Weight Capacity (kg' : mean_test_weight},inplace=True)

In [239]:
x_test = pd.get_dummies(test_data,cat_columns,drop_first=True).drop('id',axis=1).values

In [240]:
x_test

array([[2.0, 20.671146610744945, False, ..., True, False, False],
       [7.0, 13.564104570506816, False, ..., True, False, False],
       [9.0, 11.80979907832244, False, ..., False, False, False],
       ...,
       [9.0, 26.89016345926996, True, ..., True, False, False],
       [10.0, 25.76915286167727, False, ..., False, False, False],
       [8.0, 29.175026261743568, False, ..., False, True, False]],
      dtype=object)

In [241]:
y_pred_test = price_tree.predict(x_test)

In [242]:
submission = pd.read_csv("data/sample_submission.csv")

In [243]:
submission['Price'] = y_pred_test

In [244]:
submission

            id      Price
0       300000  81.257216
1       300001  81.334971
2       300002  82.417721
3       300003  78.771266
4       300004  81.166608
...        ...        ...
199995  499995  79.339390
199996  499996  80.424720
199997  499997  81.125888
199998  499998  83.154069
199999  499999  80.752980

[200000 rows x 2 columns]

In [245]:
submission.to_csv("data/submission_tree15depthextra.csv",index=False)
#submission.to_csv("data/submission_tree10depth.csv", index=False)